// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE21Id_kHw1L7CBO5nDpEIez1CVb2HptM',
    appId: '1:800825431747:web:e56ec7ee0a90472f87b476',
    messagingSenderId: '800825431747',
    projectId: 'nextsight2-4db05',
    authDomain: 'nextsight2-4db05.firebaseapp.com',
    storageBucket: 'nextsight2-4db05.firebasestorage.app',
    measurementId: 'G-JD1VM2CTNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU2XM4fmgnRiQm2QwGDDRZR7saEpzOUi4',
    appId: '1:800825431747:android:27259ff5ab7e8c9e87b476',
    messagingSenderId: '800825431747',
    projectId: 'nextsight2-4db05',
    storageBucket: 'nextsight2-4db05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCslDJrVPGLepqVQ7PGn9Cf5Yi2Tkjrv9c',
    appId: '1:800825431747:ios:f367371aa1ea1f8687b476',
    messagingSenderId: '800825431747',
    projectId: 'nextsight2-4db05',
    storageBucket: 'nextsight2-4db05.firebasestorage.app',
    iosClientId: '800825431747-vhq5u53p59bvpqdf68eefne8d4bdn11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextsight20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCslDJrVPGLepqVQ7PGn9Cf5Yi2Tkjrv9c',
    appId: '1:800825431747:ios:f367371aa1ea1f8687b476',
    messagingSenderId: '800825431747',
    projectId: 'nextsight2-4db05',
    storageBucket: 'nextsight2-4db05.firebasestorage.app',
    iosClientId: '800825431747-vhq5u53p59bvpqdf68eefne8d4bdn11g.apps.googleusercontent.com',
    iosBundleId: 'com.example.nextsight20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE21Id_kHw1L7CBO5nDpEIez1CVb2HptM',
    appId: '1:800825431747:web:2b7835d7298da6cb87b476',
    messagingSenderId: '800825431747',
    projectId: 'nextsight2-4db05',
    authDomain: 'nextsight2-4db05.firebaseapp.com',
    storageBucket: 'nextsight2-4db05.firebasestorage.app',
    measurementId: 'G-7DZSMWYENB',
  );
}
